### PR TITLE
SphereX

### PR DESCRIPTION
**Pull request by ArielTM**

### CODE REVIEW

**Review by emilyJLin95 — CHANGES_REQUESTED** [review]
Seems like the image link is broken?

Screenshot 2024-01-29 at 12 27 53 PM

**Review by emilyJLin95 — APPROVED** [review]
LGTM

**Comment by ArielTM** [comment]
Thanks @emilyJLin95 ! anything else needed to merge this?

**Comment by emilyJLin95** [comment]
> Thanks @emilyJLin95 ! anything else needed to merge this?

merged! Just was waiting for the checks to pass!

**Pull request merged**
