### PR TITLE
Add Arkham under Data Indexers & Analytics

### PR DESCRIPTION
**Pull request by ARKHAM-Alex**

### CODE REVIEW

**Review by emilyJLin95 — CHANGES_REQUESTED** [review]
Can you run add Arkham  to `project-words.txt` and run `npm run lint` tom make sure there are no errors?

**Review by emilyJLin95 — CHANGES_REQUESTED** [review]
Ah I forgot to ask

You need to add arkham to sidebars.js for it to show up under the left column

can you check locally that it is probably displaying?

**Comment by ARKHAM-Alex** [comment]
> Ah I forgot to ask
> 
> You need to add arkham to sidebars.js for it to show up under the left column
> 
> can you check locally that it is probably displaying?

>added

**Review by emilyJLin95 — APPROVED** [review]
LGTM

**Comment by ARKHAM-Alex** [comment]
🤝

**Pull request merged**
