### PR TITLE
Add Etherspot 

### PR DESCRIPTION
**Pull request by arddluma**
Added Etherspot - Account Abstraction development platform

Web: https://etherspot.io
Docs: https://etherspot.fyi

### CODE REVIEW

**Review by emilyJLin95 — CHANGES_REQUESTED** [review]
Can you run `npm run lint` and modify `project-words.txt` so the lint checker passes?
@arddluma

**Comment by arddluma** [comment]
> Can you run `npm run lint` and modify `project-words.txt` so the lint checker passes? @arddluma

hey,
Apologies for late reply. Could you please double check ? 
Thank you!

**Review by emilyJLin95 — CHANGES_REQUESTED** [review]
hihi looks like lint is still failing?

```
/home/runner/work/doc.zk-evm/doc.zk-evm/docs/build-on-linea/tooling/account-abstraction/etherspot.md:13:6 - Unknown word (Skandha)
/home/runner/work/doc.zk-evm/doc.zk-evm/docs/build-on-linea/tooling/account-abstraction/etherspot.md:15:6 - Unknown word (Arka)
```
@arddluma

**Comment by arddluma** [comment]
> hihi looks like lint is still failing?
> 
> ```
> /home/runner/work/doc.zk-evm/doc.zk-evm/docs/build-on-linea/tooling/account-abstraction/etherspot.md:13:6 - Unknown word (Skandha)
> /home/runner/work/doc.zk-evm/doc.zk-evm/docs/build-on-linea/tooling/account-abstraction/etherspot.md:15:6 - Unknown word (Arka)
> ```
> 
> @arddluma

lol I did run it locally and it passed just fine.

**Comment by arddluma** [comment]
> hihi looks like lint is still failing?
> 
> ```
> /home/runner/work/doc.zk-evm/doc.zk-evm/docs/build-on-linea/tooling/account-abstraction/etherspot.md:13:6 - Unknown word (Skandha)
> /home/runner/work/doc.zk-evm/doc.zk-evm/docs/build-on-linea/tooling/account-abstraction/etherspot.md:15:6 - Unknown word (Arka)
> ```
> 
> @arddluma

one more try ?!

**Comment by arddluma** [comment]
> LGTM

yoooo finally 🔥🔥🔥
ty

**Pull request merged**
