### PR TITLE
adding dune to tooling section

### PR DESCRIPTION
**Pull request by 0xBoxer**
Adding Dune to the tool and infrastructure sections, specifically to the data indexer and Analytics sections. 

I've also taken the liberty and ordered these alphabetically.

I've run a local build successfully and checked all links and references for correctness.

### CODE REVIEW

**Review by emilyJLin95 — CHANGES_REQUESTED** [review]
Can you add datashare to `project-words.txt` and run `npm run lint` to make sure it all builds

**Comment by 0xBoxer** [comment]
@emilyJLin95 fixed now, sorry about that

**Review by jlwllmr — CHANGES_REQUESTED** [review]
Some minor changes required to align with house style, but otherwise LGTM — can merge once resolved!

**Comment by 0xBoxer** [comment]
thanks for the help @emilyJLin95 🙏

**Review by jlwllmr — APPROVED** [review]
LGTM!

**Pull request merged**
