### PR TITLE
Adding Noves to dev tooling

### PR DESCRIPTION
**Pull request by juanlenoves**
Noves is a Linea ecosystem partner (we operate Linea for Humans).

In this PR we submit an additional two files to get our API listed for the account abstraction and data indexing categories.

### CODE REVIEW

**Review by emilyJLin95 — CHANGES_REQUESTED** [review]
Can you add Noves to `project-words.txt`

**Comment by juanlenoves** [comment]
> Can you add Noves to `project-words.txt`

Done!

**Review by emilyJLin95 — CHANGES_REQUESTED** [review]
Ah I forgot to mention! If you want the tabs to show up in the sidebar, you need to add your labels to `sidebars.js`

**Comment by juanlenoves** [comment]
> Ah I forgot to mention! If you want the tabs to show up in the sidebar, you need to add your labels to `sidebars.js`

Thanks! Also added that

**Review by emilyJLin95 — APPROVED** [review]
LGTM

**Pull request merged**
